services:

  ctfd:
    build: ctfd/ctfd:3.7.4
    container_name: ctfd
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://ctfd:ctfd@db/ctfd
      SECRET_KEY: supersecretkey

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ctfd_data:/opt/CTFd/.data

    networks:
      - labnet

  db:
    image: postgres:15
    container_name: ctfd-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ctfd
      POSTGRES_USER: ctfd
      POSTGRES_PASSWORD: ctfd

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctfd"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - labnet

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    restart: unless-stopped

    ports:
      - "3000:3000"

    networks:
      - labnet

networks:
  labnet:

volumes:
  postgres_data:
  ctfd_data:
